<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsMailer\Factory\MailTransportFactory'       => __DIR__ . '/src/Factory/MailTransportFactory.php',
    'CmsMailer\Initializer\MailServiceInitializer' => __DIR__ . '/src/Initializer/MailServiceInitializer.php',
    'CmsMailer\Module'                             => __DIR__ . '/src/Module.php',
    'CmsMailer\Mvc\Controller\AdminController'     => __DIR__ . '/src/Mvc/Controller/AdminController.php',
    'CmsMailer\Service\MailService'                => __DIR__ . '/src/Service/MailService.php',
    'CmsMailer\Service\MailServiceAwareInterface'  => __DIR__ . '/src/Service/MailServiceAwareInterface.php',
    'CmsMailer\Service\MailServiceAwareTrait'      => __DIR__ . '/src/Service/MailServiceAwareTrait.php',
    'CmsMailer\Service\MailServiceInterface'       => __DIR__ . '/src/Service/MailServiceInterface.php',
    'CmsMailerTest\Framework\TestCase'             => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsMailerTest\SampleTest'                     => __DIR__ . '/tests/SampleTest.php',
);
